version: '3.9'
services:
    web:
        build: .
        ports:
          - "5000:5000"
        volumes:
          - .:/app
        command: python app/main.py
        environment:
          - FLASK_ENV=development